# Generated by Django 3.2.22 on 2023-11-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buy_price",
            field=models.DecimalField(decimal_places=2, default=True, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="memberbucks_only",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, default=True, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api_shop.supplier",
            ),
            preserve_default=False,
        ),
    ]
