# Generated by Django 3.2.25 on 2024-05-31 03:39

from django.db import migrations, models
import django.utils.timezone
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data", models.JSONField(verbose_name="Data")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("member_count_total", "Member Count Total"),
                            ("subscription_count_total", "Subscription Count Total"),
                        ],
                        default=None,
                        max_length=250,
                        verbose_name="Metric Name",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("metric"),
                models.Model,
            ),
        ),
    ]
