# Generated by Django 3.2.25 on 2024-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(
                choices=[
                    ("member_count_total", "Member Count Total"),
                    ("member_count_6_months", "Member Count 6 Months"),
                    ("member_count_12_months", "Member Count 12 Months"),
                    ("subscription_count_total", "Subscription Count Total"),
                ],
                default=None,
                max_length=250,
                verbose_name="Metric Name",
            ),
        ),
    ]
