# Generated by Django 3.2.25 on 2024-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0002_alter_metric_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(
                choices=[
                    ("member_count_total", "Member Count Total"),
                    ("member_count_6_months_total", "Member Count 6 Months"),
                    ("member_count_12_months_total", "Member Count 12 Months"),
                    ("subscription_count_total", "Subscription Count Total"),
                    ("memberbucks_balance_total", "Memberbucks Balance Total"),
                    (
                        "memberbucks_transactions_total",
                        "Memberbucks Transactions Total",
                    ),
                ],
                default=None,
                max_length=250,
                verbose_name="Metric Name",
            ),
        ),
    ]
