# Generated by Django 3.1.4 on 2020-12-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Description"
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Stripe Id"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Is this plan visible to members?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Stripe Id"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="Is this plan visible to members?"
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        verbose_name="The cost in cents for this payment plan."
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        verbose_name="The interval the price is charged at (per billing period)."
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Months", "months"),
                            ("Weeks", "weeks"),
                            ("Days", "days"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "member_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_admin_tools.membertier",
                    ),
                ),
            ],
        ),
    ]
