# Generated by Django 3.1.4 on 2021-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_admin_tools", "0002_auto_20210102_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="interval_count",
            field=models.IntegerField(
                verbose_name="How frequently the price is charged at (per billing interval)."
            ),
        ),
    ]
