# Generated by Django 3.1.4 on 2021-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_admin_tools", "0004_paymentplan_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Name"),
        ),
    ]
