# Generated by Django 3.1.4 on 2021-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_admin_tools", "0005_auto_20210102_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertier",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Is this plan featured?"
            ),
        ),
    ]
