# Generated by Django 3.2.2 on 2021-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0007_auto_20210107_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertier",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
