# Generated by Django 3.2.12 on 2022-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0008_auto_20211005_0015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="cost",
            field=models.IntegerField(
                verbose_name="The cost in cents for this membership plan."
            ),
        ),
    ]
