# Generated by Django 3.2.19 on 2023-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_admin_tools", "0009_alter_paymentplan_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertier",
            name="description",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="membertier",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
