# Generated by Django 3.2.25 on 2024-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_admin_tools", "0010_auto_20230729_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="interval",
            field=models.CharField(
                choices=[("Month", "month"), ("Week", "week"), ("Day", "day")],
                max_length=10,
            ),
        ),
    ]
