services:
  mm-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=membermatters
      - POSTGRES_PASSWORD=membermatters
      - POSTGRES_DB=membermatters
    ports:
      - "5432:5432"
    volumes:
      - mm-postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "membermatters", "-d", "membermatters"]
      start_period: 1m
      start_interval: 1s

  # MemberMatters Redis
  mm-redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1m
      start_interval: 1s

  # MemberMatters
  mm-webapp:
    image: membermatters/membermatters
    pull_policy: build
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      MM_ENV: "Production"
      MM_SECRET_KEY: "CHANGE_ME"
      MM_USE_POSTGRES: True
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      mm-postgres:
        condition: service_healthy
      mm-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:800[0-1]/api/config/"]
      start_period: 1m
      start_interval: 1s
      retries: 5

  # MemberMatters Celery Worker
  mm-celery-worker:
    image: membermatters/membermatters
    pull_policy: build
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      MM_ENV: "Production"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_worker"
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    depends_on:
      mm-webapp:
        condition: service_healthy
        restart: true
      mm-redis:
        condition: service_healthy
        restart: true

  # MemberMatters Celery Beat
  mm-celery-beat:
    image: membermatters/membermatters
    pull_policy: build
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      MM_ENV: "Production"
      MM_USE_POSTGRES: True
      MM_RUN_MODE: "celery_beat"
      MM_REDIS_HOST: "redis://mm-redis:6379/0"
    depends_on:
      mm-webapp:
        condition: service_healthy
        restart: true
      mm-redis:
        condition: service_healthy
        restart: true

  mm-celery-prom-exporter:
    image: danihodovic/celery-exporter
    restart: always
    environment:
      CE_BROKER_URL: "redis://mm-redis:6379/0"
    depends_on:
      mm-celery-worker:
        condition: service_started
        restart: true
      mm-redis:
        condition: service_healthy
        restart: true

volumes:
  mm-postgres-volume:
    driver: local
