# Generated by Django 3.0.4 on 2020-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("agm", "Annual General"),
                    ("group", "Group"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="Meeting Type",
            ),
        ),
    ]
