# Generated by Django 3.2.2 on 2021-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_meeting", "0002_auto_20201118_2210"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="group",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("agm", "Annual General"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="Meeting Type",
            ),
        ),
        migrations.AlterField(
            model_name="proxyvote",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
