# Generated by Django 3.0.4 on 2020-03-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_meeting", "0002_auto_20200327_0046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="chair",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
