# Generated by Django 3.0.4 on 2020-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_meeting", "0003_auto_20200329_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxyvote",
            name="proxy_city",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="proxyvote",
            name="user_city",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
