# Generated by Django 2.0.7 on 2018-07-31 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceBucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('transaction_type', models.CharField(choices=[('stripe', 'Stripe Payment'), ('bank', 'Bank Transfer'), ('card', 'Membership Card')], max_length=10, verbose_name='Transaction Type')),
                ('description', models.CharField(max_length=100, verbose_name='Description of Transaction')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('logging_info', models.TextField(blank=True, verbose_name='Detailed logging info from stripe.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
