# Generated by Django 3.2.13 on 2022-06-12 01:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(verbose_name="Name")),
                (
                    "description",
                    models.TextField(default="", verbose_name="Description"),
                ),
                ("location", models.TextField(default="", verbose_name="Location")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ical", "iCal Calendar Feed"),
                            ("other", "Other Source"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("uid_external", models.TextField(default=uuid.uuid4, unique=True)),
                (
                    "date_updated_external",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "repeat_rule_ical",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Repeat Rule (iCal)",
                    ),
                ),
            ],
        ),
    ]
