# Generated by Django 2.0 on 2018-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True, verbose_name="Cause Name")),
                ("description", models.CharField(max_length=100, verbose_name="Cause Description")),
            ],
        ),
    ]
