# Generated by Django 3.0.10 on 2020-11-18 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leaders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
