# Generated by Django 3.1.4 on 2021-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0003_auto_20201210_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Cause Description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Cause Name"
            ),
        ),
    ]
