# Generated by Django 3.1.8 on 2021-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0005_auto_20210306_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Cause Description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Cause Name"
            ),
        ),
    ]
