# Generated by Django 3.0.2 on 2020-01-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0006_auto_20200127_1112"),
    ]

    operations = [
        migrations.RenameField(
            model_name="causefund",
            old_name="cause",
            new_name="group",
        ),
    ]
