# Generated by Django 3.1.8 on 2021-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_auto_20210428_2149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Cause Description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Cause Name"
            ),
        ),
    ]
