# Generated by Django 3.0.4 on 2020-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_auto_20200127_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Cause Description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Cause Name"
            ),
        ),
    ]
