# Generated by Django 3.2.2 on 2021-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0008_auto_20210429_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Name"),
        ),
    ]
