# Generated by Django 3.0.5 on 2020-04-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0008_auto_20200326_2011"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": [
                    ("see_member_groups", "Can see groups"),
                    ("add_member_group", "Can add a new group"),
                    ("manage_member_group", "Can manage a group"),
                ]
            },
        ),
        migrations.DeleteModel(name="CauseFund",),
    ]
