# Generated by Django 3.2.2 on 2021-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0009_auto_20211005_0015"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
        migrations.RemoveField(
            model_name="group",
            name="account_code",
        ),
        migrations.RemoveField(
            model_name="group",
            name="description",
        ),
        migrations.RemoveField(
            model_name="group",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="group",
            name="item_code",
        ),
        migrations.RemoveField(
            model_name="group",
            name="leaders",
        ),
        migrations.RemoveField(
            model_name="group",
            name="name",
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
