# Generated by Django 3.0.5 on 2020-04-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0009_auto_20200405_1813"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": [
                    ("manage_member_groups", "Can manage member groups"),
                    ("add_member_group", "Can add a new member group"),
                    ("manage_member_group", "Can manage a member group"),
                ],
                "verbose_name": "Member Group",
                "verbose_name_plural": "Member Groups",
            },
        ),
    ]
