# Generated by Django 3.2.2 on 2021-10-04 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0010_auto_20211005_0017"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
    ]
