# Generated by Django 3.0.5 on 2020-04-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0010_auto_20200405_1819"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "permissions": [("manage_member_groups", "Can manage member groups")],
                "verbose_name": "Member Group",
                "verbose_name_plural": "Member Groups",
            },
        ),
    ]
