# Generated by Django 3.1.8 on 2021-04-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberbucks', '0002_memberbucks_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberbucks',
            options={'verbose_name': 'Memberbucks', 'verbose_name_plural': 'Memberbucks'},
        ),
    ]
