# Generated by Django 3.0.2 on 2020-01-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberbucks", "0002_auto_20181018_1949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberbucks",
            name="fund",
        ),
    ]
