# Generated by Django 3.2.13 on 2022-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberbucks", "0004_alter_memberbucks_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberbucks",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe Top-up"),
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("card", "Membership Card"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="Transaction Type",
            ),
        ),
    ]
