# Generated by Django 3.2.20 on 2023-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberbucks", "0005_alter_memberbucks_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberbucks",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe Top-up"),
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("card", "Membership Card"),
                    ("interlock", "Interlock Cost"),
                    ("other", "Other"),
                ],
                max_length=10,
                verbose_name="Transaction Type",
            ),
        ),
    ]
