# Generated by Django 3.2.25 on 2024-05-23 05:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0016_auto_20240523_1550"),
        ("memberbucks", "0006_alter_memberbucks_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberbucksProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Description of product",
                    ),
                ),
                (
                    "image_url",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Product image",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "external_id_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="External ID human-readable name",
                    ),
                ),
                (
                    "stock_level",
                    models.IntegerField(
                        default=0,
                        verbose_name="Number of this product left and available to dispense.",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        verbose_name="Price in cents to be charged to the end user."
                    ),
                ),
                (
                    "cost_price",
                    models.IntegerField(
                        verbose_name="Price in cents that it costs to buy this product."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberbucksProductPurchaseLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "price",
                    models.IntegerField(
                        verbose_name="Price in cents that was charged to the end user."
                    ),
                ),
                (
                    "cost_price",
                    models.IntegerField(
                        verbose_name="Price in cents that it costs to buy this product."
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "memberucks_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access.memberbucksdevice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memberbucks.memberbucksproduct",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
