# Generated by Django 3.2.25 on 2024-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberbucks", "0007_memberbucksproduct_memberbucksproductpurchaselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberbucks",
            name="description",
            field=models.CharField(
                max_length=500, verbose_name="Description of Transaction"
            ),
        ),
    ]
