# Generated by Django 3.1.4 on 2020-12-29 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membertypes",
            name="description",
        ),
    ]
