# Generated by Django 2.1 on 2018-08-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xero_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
