# Generated by Django 3.1.4 on 2021-01-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_admin_tools", "0007_auto_20210107_1133"),
        ("profile", "0002_remove_membertypes_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="membership_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership_plan",
                to="api_admin_tools.paymentplan",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
