# Generated by Django 2.1 on 2018-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_profile_xero_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='xero_id',
            new_name='xero_account_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='xero_account_number',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
