# Generated by Django 3.1.4 on 2021-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_auto_20210107_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("active", "Active"),
                    ("cancelling", "Cancelling"),
                ],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
