# Generated by Django 3.1.8 on 2021-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_auto_20210218_1100"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membertypes",
            options={
                "verbose_name": "Member types",
                "verbose_name_plural": "Member types",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                choices=[
                    ("noob", "Needs Induction"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("accountonly", "Account only"),
                ],
                default="noob",
                max_length=11,
            ),
        ),
    ]
