# Generated by Django 2.0 on 2018-08-11 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20180806_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.FileField(blank=True, null=True, upload_to='themes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_invoice',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
