# Generated by Django 2.0 on 2018-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20180811_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
