# Generated by Django 3.2.13 on 2022-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_auto_20220425_2328"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vehicle_registration_plate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
