# Generated by Django 3.2.19 on 2023-05-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0010_profile_vehicle_registration_plate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exclude_from_email_export",
            field=models.BooleanField(default=False),
        ),
    ]
