# Generated by Django 3.2.20 on 2023-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0012_alter_log_logtype"),
    ]

    def set_subscription_first_created(apps, schema_editor):
        Profile = apps.get_model("profile", "Profile")
        for profile in Profile.objects.all():
            if profile.subscription_first_created is None:
                profile.subscription_first_created = profile.created
                profile.save()

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_first_created",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
        migrations.RunPython(set_subscription_first_created),
    ]
