# Generated by Django 3.2.20 on 2023-10-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0015_alter_accesscontrolleddevice_ip_address"),
        ("profile", "0013_profile_subscription_first_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="door",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="access.doors",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="interlock",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="access.interlock",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="memberbucks_device",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="access.memberbucksdevice",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="logtype",
            field=models.CharField(
                choices=[
                    ("generic", "Generic log entry"),
                    ("usage", "Generic usage access"),
                    ("stripe", "Stripe related event"),
                    ("memberbucks", "Memberbucks related event"),
                    ("spacebucks", "Spacebucks related event"),
                    ("profile", "Member profile was edited or updated"),
                    ("interlock", "Interlock device related event"),
                    ("door", "Door device related event"),
                    ("memberbucksdevice", "Memberbucks device related event"),
                    ("email", "An email was sent or attempted to be sent"),
                    ("admin", "An admin performed an action"),
                    ("error", "An event or action caused an error"),
                    ("xero", "Generic xero log entry"),
                ],
                max_length=30,
                verbose_name="Type of action/event",
            ),
        ),
    ]
