# Generated by Django 2.1.15 on 2020-01-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20190227_2353'),
        ('profile', '0010_profile_last_induction'),
    ]

    operations = [
    ]
