# Generated by Django 3.2.20 on 2023-10-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0015_alter_log_logtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="data",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Extra data for debugging action/event",
            ),
        ),
    ]
