# Generated by Django 3.0.2 on 2020-01-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0007_auto_20200127_1209"),
        ("profile", "0016_auto_20200127_1112"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="group",
            new_name="groups",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="can_add_cause",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="can_manage_cause",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="can_manage_causes",
        ),
        migrations.AddField(
            model_name="profile",
            name="can_add_group",
            field=models.BooleanField(default=False, verbose_name="Can add a Group"),
        ),
        migrations.AddField(
            model_name="profile",
            name="can_manage_group",
            field=models.ManyToManyField(blank=True, related_name="can_manage_group", to="group.Group"),
        ),
        migrations.AddField(
            model_name="profile",
            name="can_manage_groups",
            field=models.BooleanField(default=False, verbose_name="Can manage Group"),
        ),
    ]
