# Generated by Django 3.2.20 on 2024-01-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0016_alter_log_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="logtype",
            field=models.CharField(
                choices=[
                    ("generic", "Generic Event"),
                    ("stripe", "Stripe Event"),
                    ("memberbucks", "Memberbucks Updated"),
                    ("spacebucks", "Spacebucks Updated"),
                    ("profile", "Member Profile Updated"),
                    ("interlock", "Interlock Event"),
                    ("door", "Door Event"),
                    ("memberbucksdevice", "Memberbucks Event"),
                    ("email", "Email Sent"),
                    ("sms", "SMS Sent"),
                    ("admin", "Admin Action"),
                    ("error", "Unhandled Error"),
                    ("xero", "Xero Event"),
                ],
                default="generic",
                max_length=30,
                verbose_name="Type of action/event",
            ),
        ),
    ]
