# Generated by Django 3.2.25 on 2025-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0017_alter_log_logtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_pronouns",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Preferred Pronouns"
            ),
        ),
    ]
