# Generated by Django 3.2.25 on 2025-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_alter_log_logtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memberdoc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
