# Generated by Django 3.2.25 on 2025-01-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_profile_memberdoc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='memberdoc_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
