# Generated by Django 3.0.2 on 2020-02-02 04:11

import django.core.validators
from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_auto_20200127_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=profile.models.Profile.path_and_rename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0417123456'.Up to 12 characters allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
