# Generated by Django 3.0.4 on 2020-03-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0021_auto_20200202_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="can_add_group",
            field=models.BooleanField(default=False, verbose_name="Can add a Cause"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="can_manage_groups",
            field=models.BooleanField(default=False, verbose_name="Can manage Cause"),
        ),
    ]
