# Generated by Django 3.0.4 on 2020-03-29 09:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0023_auto_20200327_0046"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="digital_id_token",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="Digital ID Token"),
        ),
        migrations.AddField(
            model_name="profile",
            name="digital_id_token_expire",
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
