# Generated by Django 3.0.4 on 2020-03-29 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0024_auto_20200329_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="digital_id_token_expire",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
