# Generated by Django 3.0.4 on 2020-03-29 10:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0025_auto_20200329_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="digital_id_token",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                verbose_name="Digital ID Token",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="digital_id_token_expire",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, editable=False, null=True
            ),
        ),
    ]
