# Generated by Django 3.0.5 on 2020-04-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0026_auto_20200329_2047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("change_staff", "Can change if the user is a staff member or not"),
                    ("manage_access", "Can manage a user's access permissions"),
                    ("deactivate_member", "Can deactivate or activate a member"),
                    (
                        "see_personal_details",
                        "Can see and update a member's personal details",
                    ),
                    (
                        "manage_memberbucks_balance",
                        "Can see and modify memberbucks balance",
                    ),
                    ("member_logs", "Can see a members log"),
                    ("generate_invoice", "Can generate a member invoice"),
                ]
            },
        ),
        migrations.RemoveField(model_name="profile", name="can_add_group",),
        migrations.RemoveField(model_name="profile", name="can_disable_members",),
        migrations.RemoveField(model_name="profile", name="can_generate_invoice",),
        migrations.RemoveField(model_name="profile", name="can_manage_access",),
        migrations.RemoveField(model_name="profile", name="can_manage_doors",),
        migrations.RemoveField(model_name="profile", name="can_manage_group",),
        migrations.RemoveField(model_name="profile", name="can_manage_groups",),
        migrations.RemoveField(model_name="profile", name="can_manage_interlocks",),
        migrations.RemoveField(model_name="profile", name="can_see_members_logs",),
        migrations.RemoveField(
            model_name="profile", name="can_see_members_memberbucks",
        ),
        migrations.RemoveField(
            model_name="profile", name="can_see_members_personal_details",
        ),
        migrations.RemoveField(model_name="profile", name="updated_starving_details",),
    ]
