# Generated by Django 3.0.7 on 2020-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0027_auto_20200405_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                choices=[
                    ("noob", "New"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="noob",
                max_length=8,
            ),
        ),
    ]
