# Generated by Django 3.0.7 on 2020-08-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0028_auto_20200804_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
