# Generated by Django 3.0.10 on 2020-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0030_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertypes',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='membertypes',
            name='cost',
            field=models.IntegerField(verbose_name='Monthly Cost (cents)'),
        ),
    ]
