# Generated by Django 3.0.5 on 2020-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "kioskId",
                    models.CharField(
                        max_length=70, unique=True, verbose_name="Kiosk Id"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="IP Address of device",
                    ),
                ),
                ("last_seen", models.DateTimeField(null=True)),
                (
                    "play_theme",
                    models.BooleanField(
                        default=False, verbose_name="Play theme on door swipe"
                    ),
                ),
            ],
        ),
    ]
