# Generated by Django 3.0.10 on 2020-11-18 12:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verification_token", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "kiosk_id",
                    models.CharField(
                        max_length=70, unique=True, verbose_name="Kiosk Id"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="IP Address of device",
                    ),
                ),
                ("last_seen", models.DateTimeField(null=True)),
                (
                    "play_theme",
                    models.BooleanField(
                        default=False, verbose_name="Play theme on door swipe"
                    ),
                ),
                (
                    "authorised",
                    models.BooleanField(
                        default=False, verbose_name="Is this kiosk authorised?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signin_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("signout_date", models.DateTimeField(blank=True, null=True)),
                ("guests", models.TextField(default="[]")),
            ],
        ),
    ]
