# Generated by Django 3.0.5 on 2020-05-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_general", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kiosk", old_name="kioskId", new_name="kiosk_id",
        ),
    ]
