# Generated by Django 3.2.2 on 2021-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_general", "0002_auto_20201118_2210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="kiosk",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sitesession",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
