# Generated by Django 3.0.5 on 2020-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_general", "0002_auto_20200519_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="authorised",
            field=models.BooleanField(
                default=False, verbose_name="Is this kiosk authorised?"
            ),
        ),
    ]
