# Generated by Django 3.0.7 on 2020-06-06 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_general", "0003_kiosk_authorised"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signin_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("signout_date", models.DateTimeField(blank=True, null=True)),
                ("guests", models.TextField(default="[]")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
