# Generated by Django 2.0.7 on 2018-07-20 18:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action taken')),
                ('description', models.CharField(max_length=500, verbose_name='Description of why')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('log_member', models.ForeignKey(on_delete='Name of member', related_name='log_member', to=settings.AUTH_USER_MODEL)),
                ('log_user', models.ForeignKey(on_delete='Name of admin', related_name='log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Cause Name')),
                ('description', models.CharField(max_length=100, verbose_name='Cause Description')),
            ],
        ),
        migrations.CreateModel(
            name='DoorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Door Name')),
                ('description', models.CharField(max_length=100, verbose_name='Door Description/Location')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP Address of Door')),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('all_members', models.BooleanField(default=False, verbose_name='Members have access by default')),
            ],
        ),
        migrations.CreateModel(
            name='MemberTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Member Type Name')),
                ('conditions', models.CharField(max_length=100, verbose_name='Membership Conditions')),
                ('cost', models.IntegerField(verbose_name='Monthly Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('noob', 'New Member'), ('active', 'Active Member'), ('inactive', 'Inactive Member')], default='noob', max_length=8)),
                ('rfid', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RFID Tag')),
                ('causes', models.ManyToManyField(to='portal.Causes')),
                ('doors', models.ManyToManyField(blank=True, to='portal.Doors')),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_type', to='portal.MemberTypes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceBucks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10, verbose_name='Transaction Type')),
                ('description', models.CharField(max_length=100, verbose_name='Description of Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doorlog',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Doors'),
        ),
        migrations.AddField(
            model_name='doorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
