# Generated by Django 2.0.6 on 2018-06-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='member_type',
        ),
    ]
