# Generated by Django 2.0.7 on 2018-07-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_doors_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='doors',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
