# Generated by Django 2.0.6 on 2018-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20180619_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cause1',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cause 1', related_name='Cause1', to='portal.Causes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause2',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cause 2', related_name='Cause2', to='portal.Causes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause3',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cause 3', related_name='Cause3', to='portal.Causes'),
        ),
    ]
