# Generated by Django 2.0.7 on 2018-07-20 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180720_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 20, 18, 34, 56, 586991)),
        ),
    ]
