# Generated by Django 2.0.6 on 2018-06-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20180619_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cause1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cause1', to='portal.Causes', verbose_name='Cause 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cause2', to='portal.Causes', verbose_name='Cause 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cause3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cause3', to='portal.Causes', verbose_name='Cause 3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_type', to='portal.MemberTypes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
