# Generated by Django 2.0.7 on 2018-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180721_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacebucks',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='spacebucks_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
