# Generated by Django 2.0.6 on 2018-06-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180620_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causes',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cause Name'),
        ),
    ]
