# Generated by Django 2.0.6 on 2018-06-21 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0007_auto_20180620_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Door Name')),
                ('description', models.CharField(max_length=100, verbose_name='Door Description/Location')),
            ],
        ),
        migrations.AlterField(
            model_name='causes',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cause Name'),
        ),
        migrations.AddField(
            model_name='doorpermissions',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Doors'),
        ),
        migrations.AddField(
            model_name='doorpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
