# Generated by Django 2.0.7 on 2018-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180722_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacebucks',
            name='transaction_type',
            field=models.CharField(choices=[('stripe', 'Stripe Payment'), ('card', 'Membership Card')], max_length=10, verbose_name='Transaction Type'),
        ),
    ]
