# Generated by Django 2.0.6 on 2018-06-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180621_0734'),
        ('portal', '0009_auto_20180623_1842'),
    ]

    operations = [
    ]
