# Generated by Django 2.0.7 on 2018-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180722_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_card_expiry',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_card_last_digits',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
