# Generated by Django 2.0.7 on 2018-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20180722_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacebucks',
            name='logging_info',
            field=models.TextField(blank=True, verbose_name='Detailed loggin info from stripe.'),
        ),
    ]
