# Generated by Django 2.0.6 on 2018-06-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_merge_20180624_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Name of admin')),
                ('action', models.CharField(max_length=50, verbose_name='Action taken')),
                ('member', models.CharField(max_length=50, verbose_name='Name of member')),
                ('description', models.CharField(max_length=50, verbose_name='Description of why')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
