# Generated by Django 2.0.7 on 2018-07-24 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0011_spacebucks_logging_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generic', 'Generic log entry'), ('usage', 'Generic usage access'), ('stripe', 'Stripe related event'), ('spacebucks', 'Spacebucks related event'), ('profile', 'Member profile edited'), ('interlock', 'Interlock related event'), ('door', 'Door related event'), ('email', 'Email send event'), ('admin', 'Generic admin event'), ('error', 'Some event that causes an error')], max_length=30, verbose_name='Type of action/event')),
                ('description', models.CharField(max_length=500, verbose_name='Description of action/event')),
                ('data', models.TextField(verbose_name='Extra data for debugging action/event')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generic', 'Generic log entry'), ('usage', 'Generic usage access'), ('stripe', 'Stripe related event'), ('spacebucks', 'Spacebucks related event'), ('profile', 'Member profile edited'), ('interlock', 'Interlock related event'), ('door', 'Door related event'), ('email', 'Email send event'), ('admin', 'Generic admin event'), ('error', 'Some event that causes an error')], max_length=30, verbose_name='Type of action/event')),
                ('description', models.CharField(max_length=500, verbose_name='Description of action/event')),
                ('data', models.TextField(verbose_name='Extra data for debugging action/event')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete='User affected by action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='log_member',
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='log_user',
        ),
        migrations.AlterField(
            model_name='spacebucks',
            name='logging_info',
            field=models.TextField(blank=True, verbose_name='Detailed logging info from stripe.'),
        ),
        migrations.AlterField(
            model_name='spacebucks',
            name='transaction_type',
            field=models.CharField(choices=[('stripe', 'Stripe Payment'), ('bank', 'Bank Transfer'), ('card', 'Membership Card')], max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
