# Generated by Django 2.0.6 on 2018-06-24 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0011_adminlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='member',
        ),
        migrations.RemoveField(
            model_name='adminlog',
            name='user',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='log_member',
            field=models.ForeignKey(default=4, on_delete='Name of member', related_name='log_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminlog',
            name='log_user',
            field=models.ForeignKey(default=4, on_delete='Name of admin', related_name='log_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
