# Generated by Django 2.0.6 on 2018-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20180624_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description of why'),
        ),
    ]
