# Generated by Django 2.0.7 on 2018-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20180724_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
