# Generated by Django 2.0.7 on 2018-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20180725_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_card_expiry',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_card_last_digits',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
