# Generated by Django 2.0.7 on 2018-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20180725_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_expire',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_key',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
