# Generated by Django 2.0.6 on 2018-07-02 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0014_auto_20180624_0757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doorpermissions',
            unique_together={('user', 'door')},
        ),
    ]
