# Generated by Django 2.0.6 on 2018-07-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_profile_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rfid',
            field=models.CharField(max_length=20, unique=True, verbose_name='RFID Tag'),
        ),
    ]
