# Generated by Django 2.0.6 on 2018-07-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20180703_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='doors',
            name='mac_address',
            field=models.CharField(default='12:34:56:78:91:23:45:67', max_length=100, verbose_name='Door Description/Location'),
            preserve_default=False,
        ),
    ]
