# Generated by Django 2.0.6 on 2018-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_doors_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doors',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='doors',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=16, verbose_name='IP Address of Door'),
            preserve_default=False,
        ),
    ]
