# Generated by Django 2.0.6 on 2018-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20180703_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='ip_address',
            field=models.CharField(max_length=16, unique=True, verbose_name='IP Address of Door'),
        ),
    ]
