# Generated by Django 2.0.7 on 2018-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20180716_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='doors',
            name='all_members',
            field=models.BooleanField(default=False, verbose_name='Members have access by default'),
        ),
    ]
