# Generated by Django 2.0.7 on 2018-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20180716_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP Address of Door'),
        ),
    ]
