# Generated by Django 2.0.7 on 2018-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20180716_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='door_access',
            new_name='doors',
        ),
    ]
