# Generated by Django 2.0.7 on 2018-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20180716_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doors',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP Address of Door'),
        ),
    ]
