# Generated by Django 2.0.7 on 2018-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20180720_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cause1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cause2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cause3',
        ),
        migrations.AddField(
            model_name='profile',
            name='causes',
            field=models.ManyToManyField(to='portal.Causes'),
        ),
    ]
