# Generated by Django 2.0.7 on 2018-07-28 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlledDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description/Location')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP Address of device')),
                ('last_seen', models.DateTimeField(null=True)),
                ('all_members', models.BooleanField(default=False, verbose_name='Members have access by default')),
            ],
        ),
        migrations.CreateModel(
            name='DoorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='InterlockLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('on_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_heartbeat', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('accesscontrolleddevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='access.AccessControlledDevice')),
            ],
            bases=('access.accesscontrolleddevice',),
        ),
        migrations.CreateModel(
            name='Interlock',
            fields=[
                ('accesscontrolleddevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='access.AccessControlledDevice')),
            ],
            bases=('access.accesscontrolleddevice',),
        ),
    ]
