# Generated by Django 3.0.10 on 2020-11-18 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessControlledDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100, verbose_name="Description/Location"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="IP Address of device",
                    ),
                ),
                ("last_seen", models.DateTimeField(null=True)),
                (
                    "all_members",
                    models.BooleanField(
                        default=False, verbose_name="Members have access by default"
                    ),
                ),
                (
                    "locked_out",
                    models.BooleanField(
                        default=False, verbose_name="Maintenance lockout enabled"
                    ),
                ),
                (
                    "play_theme",
                    models.BooleanField(
                        default=False, verbose_name="Play theme on door swipe"
                    ),
                ),
                (
                    "exempt_signin",
                    models.BooleanField(
                        default=False,
                        verbose_name="Exempt this device from requiring a sign in",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        verbose_name="Hidden from members in their access permissions screen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoorLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="InterlockLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_heartbeat",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("session_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Doors",
            fields=[
                (
                    "accesscontrolleddevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="access.AccessControlledDevice",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_doors", "Can manage doors")],
            },
            bases=("access.accesscontrolleddevice",),
        ),
        migrations.CreateModel(
            name="Interlock",
            fields=[
                (
                    "accesscontrolleddevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="access.AccessControlledDevice",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_interlocks", "Can manage interlocks")],
            },
            bases=("access.accesscontrolleddevice",),
        ),
        migrations.CreateModel(
            name="MemberbucksDevice",
            fields=[
                (
                    "accesscontrolleddevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="access.AccessControlledDevice",
                    ),
                ),
            ],
            bases=("access.accesscontrolleddevice",),
        ),
    ]
