# Generated by Django 2.0.7 on 2018-07-28 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interlocklog',
            name='interlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.Interlock'),
        ),
        migrations.AddField(
            model_name='doorlog',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.Doors'),
        ),
    ]
