# Generated by Django 2.0.9 on 2018-10-14 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0002_auto_20181006_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocklog',
            name='user_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_off', to=settings.AUTH_USER_MODEL),
        ),
    ]
