# Generated by Django 2.0.7 on 2018-07-31 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20180728_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interlocklog',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interlocklog',
            name='on_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
