# Generated by Django 2.0 on 2018-08-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20180731_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interlocklog',
            old_name='on_date',
            new_name='first_hearbeat',
        ),
        migrations.AddField(
            model_name='interlocklog',
            name='session_complete',
            field=models.BooleanField(default=False),
        ),
    ]
