# Generated by Django 2.0 on 2018-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20180804_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interlocklog',
            old_name='first_hearbeat',
            new_name='first_heartbeat',
        ),
    ]
