# Generated by Django 3.2.7 on 2022-03-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0004_auto_20211005_0015"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrolleddevice",
            name="serial_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="accesscontrolleddevice",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
