# Generated by Django 2.0.9 on 2018-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_accesscontrolleddevice_play_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolleddevice',
            name='locked_out',
            field=models.BooleanField(default=False, verbose_name='Maintenance lockout enabled'),
        ),
    ]
