# Generated by Django 2.0 on 2018-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_spacebucksdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacebucksdevice',
            name='accesscontrolleddevice_ptr',
        ),
        migrations.DeleteModel(
            name='SpacebucksDevice',
        ),
    ]
