# Generated by Django 3.2.12 on 2022-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0005_auto_20220312_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="doorlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
