# Generated by Django 3.2.13 on 2022-05-31 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0006_doorlog_success"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doors",
            options={
                "permissions": [("manage_doors", "Can manage doors")],
                "verbose_name": "Door",
                "verbose_name_plural": "Doors",
            },
        ),
    ]
