# Generated by Django 3.0.5 on 2020-04-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0007_auto_20181204_0417"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doors",
            options={"permissions": [("manage_doors", "Can manage doors")]},
        ),
        migrations.AlterModelOptions(
            name="interlock",
            options={"permissions": [("manage_interlocks", "Can manage interlocks")]},
        ),
    ]
