# Generated by Django 3.2.13 on 2022-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0007_alter_doors_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrolleddevice",
            name="report_online_status",
            field=models.BooleanField(
                default=True, verbose_name="Report the online status of this device."
            ),
        ),
    ]
