# Generated by Django 3.0.7 on 2020-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0008_auto_20200405_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrolleddevice",
            name="exempt_signin",
            field=models.BooleanField(
                default=False,
                verbose_name="Exempt this device from requiring a sign in",
            ),
        ),
    ]
