# Generated by Django 3.0.7 on 2020-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0009_accesscontrolleddevice_exempt_signin"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscontrolleddevice",
            name="hidden",
            field=models.BooleanField(
                default=False,
                verbose_name="Hidden from members in their access permissions screen",
            ),
        ),
    ]
