# Generated by Django 3.2.20 on 2023-10-09 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0011_auto_20231008_2254"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InternalAccessControlAPIKey",
            new_name="AccessControlledDeviceAPIKey",
        ),
        migrations.AlterModelOptions(
            name="accesscontrolleddeviceapikey",
            options={"verbose_name": "API Key For Access Controlled Device"},
        ),
        migrations.AlterModelOptions(
            name="externalaccesscontrolapikey",
            options={"verbose_name": "API Key For External Access Control API"},
        ),
    ]
