# Generated by Django 3.2.20 on 2023-10-11 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0013_auto_20231010_0032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interlock",
            options={},
        ),
        migrations.RenameField(
            model_name="interlocklog",
            old_name="last_heartbeat",
            new_name="date_updated",
        ),
        migrations.RenameField(
            model_name="interlocklog",
            old_name="user",
            new_name="user_started",
        ),
        migrations.RemoveField(
            model_name="interlocklog",
            name="first_heartbeat",
        ),
        migrations.RemoveField(
            model_name="interlocklog",
            name="session_complete",
        ),
        migrations.RemoveField(
            model_name="interlocklog",
            name="user_off",
        ),
        migrations.AddField(
            model_name="interlock",
            name="cost_per_hour",
            field=models.IntegerField(
                default=0, verbose_name="Cost per hour (in cents)"
            ),
        ),
        migrations.AddField(
            model_name="interlock",
            name="cost_per_kwh",
            field=models.IntegerField(
                default=0, verbose_name="Cost per kWh (in cents)"
            ),
        ),
        migrations.AddField(
            model_name="interlock",
            name="cost_per_session",
            field=models.IntegerField(
                default=0, verbose_name="Fixed cost per session (in cents)"
            ),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="date_ended",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="date_started",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="total_cost",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="total_kwh",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="total_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="interlocklog",
            name="user_ended",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
