# Generated by Django 3.2.20 on 2023-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0014_auto_20231012_0356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscontrolleddevice",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Address of device"
            ),
        ),
    ]
