# Generated by Django 3.2.25 on 2024-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0015_alter_accesscontrolleddevice_ip_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memberbucksdevice",
            options={
                "verbose_name": "Memberbucks Device",
                "verbose_name_plural": "Memberbucks Devices",
            },
        ),
        migrations.AddField(
            model_name="memberbucksdevice",
            name="supports_credits",
            field=models.BooleanField(
                default=False, verbose_name="Supports the MM simple credits API."
            ),
        ),
        migrations.AddField(
            model_name="memberbucksdevice",
            name="supports_debits",
            field=models.BooleanField(
                default=False, verbose_name="Supports the MM simple debits API."
            ),
        ),
        migrations.AddField(
            model_name="memberbucksdevice",
            name="supports_products",
            field=models.BooleanField(
                default=False, verbose_name="Supports the mm products API."
            ),
        ),
    ]
