# Generated by Django 3.2.25 on 2024-05-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0017_auto_20240523_1604"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberbucksdevice",
            name="supports_credits",
        ),
        migrations.RemoveField(
            model_name="memberbucksdevice",
            name="supports_debits",
        ),
        migrations.RemoveField(
            model_name="memberbucksdevice",
            name="supports_products",
        ),
    ]
