# Generated by Django 3.2.25 on 2024-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0018_auto_20240525_0016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscontrolleddevice",
            name="description",
            field=models.CharField(max_length=500, verbose_name="Description/Location"),
        ),
        migrations.AlterField(
            model_name="interlocklog",
            name="reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
