from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework import serializers
from access.models import DoorLog, InterlockLog
from api_general.serializers import UserSerializer
