# Generated by Django 2.0.7 on 2018-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Cause Name')),
                ('description', models.CharField(max_length=100, verbose_name='Cause Description')),
            ],
        ),
    ]
