# Generated by Django 2.0.9 on 2018-10-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='account_code',
            field=models.IntegerField(default=200, verbose_name='Account Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='causes',
            name='item_code',
            field=models.CharField(default="SET_ME", max_length=50, unique=True, verbose_name='Item Code'),
            preserve_default=False,
        ),
    ]
