# Generated by Django 2.1.5 on 2019-01-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_causes_leaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
